### ISSUE TITLE
Is there any stable version soon?

### ISSUE THREAD

**Issue by sudhinsr** [Azure/Microsoft.Extensions.Caching.Cosmos#22]
Looking for a solution that can replace Redis distributed cache with CosmosDB using less configuration headache, high SLA, and geo-replication at less price.

I'm facing ttl null issue while setting data using IDistributedCache with the current preview version.

**Comment by ealsur** [comment]
Can you share more details about the null issue? A stack trace? Something we can use to troubleshoot and reproduce the issue?

**Comment by sudhinsr** [comment]
I'm getting following exception during the set operation 

```
Microsoft.Azure.Cosmos.CosmosException
  HResult=0x80131500
  Message=Response status code does not indicate success: 400 Substatus: 0 Reason: (Microsoft.Azure.Documents.BadRequestException: Message: {"Errors":["The input ttl 'null' is invalid. Ensure to provide a nonzero positive integer less than or equal to '2147483647', or '-1' which means never expire."]}ActivityId: 00000000-0000-0000-0000-00000000000, Request URI: /apps/00000000-0000-0000-0000-00000000000/services/00000000-0000-0000-0000-00000000000/partitions/00000000-0000-0000-0000-00000000000/replicas/132351531136575315p/, RequestStats: RequestStartTime: 2020-06-01T19:03:53.3976559Z, RequestEndTime: 2020-06-01T19:03:53.5704053Z,  Number of regions attempted:1ResponseTime: 2020-06-01T19:03:53.5704053Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-westeurope1-fd13.documents.azure.com:14458/apps/00000000-0000-0000-0000-00000000000/services/00000000-0000-0000-0000-00000000000/partitions/00000000-0000-0000-0000-00000000000/replicas/132351531136575315p/, LSN: 1, GlobalCommittedLsn: 1, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 400, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: 0#1#12=-1, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Upsert, SDK: Windows/10.0.19041 cosmos-netstandard-sdk/3.4.2   at Microsoft.Azure.Documents.TransportClient.ThrowServerException(String resourceAddress, StoreResponse storeResponse, Uri physicalAddress, Guid activityId, DocumentServiceRequest request)   at Microsoft.Azure.Documents.Rntbd.TransportClient.InvokeStoreAsync(Uri physicalAddress, ResourceOperation resourceOperation, DocumentServiceRequest request)   at Microsoft.Azure.Documents.ConsistencyWriter.WritePrivateAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean forceRefresh)   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync(Func`1 callbackMethod, Func`3 callShouldRetry, Func`1 inBackoffAlternateCallbackMethod, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)   at Microsoft.Azure.Documents.ConsistencyWriter.WriteAsync(DocumentServiceRequest entity, TimeoutHelper timeout, Boolean forceRefresh, CancellationToken cancellationToken)   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass26_0.<<InvokeAsync>b__0>d.MoveNext()--- End of stack trace from previous location where exception was thrown ---   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy, Func`2 prepareRequestAsyncDelegate)   at Microsoft.Azure.Documents.ServerStoreModel.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken)   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessUpsertAsync(IStoreModel storeProxy, DocumentServiceRequest serviceRequest, CancellationToken cancellationToken)   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)).
  Source=Microsoft.Azure.Cosmos.Client
  StackTrace:
   at Microsoft.Azure.Cosmos.ResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.ToObjectInternal[T](ResponseMessage cosmosResponseMessage, CosmosSerializer jsonSerializer)
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.<CreateItemResponseAsync>b__6_0[T](ResponseMessage cosmosResponseMessage)
   at Microsoft.Azure.Cosmos.CosmosResponseFactory.<ProcessMessageAsync>d__16`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Caching.Cosmos.CosmosCache.<SetAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Solution.Cache.<StoreAsync>d__3.MoveNext() in C:\Solution\Service\Cache.cs:line 26
```

**Comment by ealsur** [comment]
Looks like the source is here: https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/master/src/CosmosCache.cs#L265

```csharp
private static long? GetExpirationInSeconds(DateTimeOffset creationTime, DateTimeOffset? absoluteExpiration, DistributedCacheEntryOptions options)
        {
            if (absoluteExpiration.HasValue && options.SlidingExpiration.HasValue)
            {
                return (long)Math.Min(
                    (absoluteExpiration.Value - creationTime).TotalSeconds,
                    options.SlidingExpiration.Value.TotalSeconds);
            }
            else if (absoluteExpiration.HasValue)
            {
                return (long)(absoluteExpiration.Value - creationTime).TotalSeconds;
            }
            else if (options.SlidingExpiration.HasValue)
            {
                return (long)options.SlidingExpiration.Value.TotalSeconds;
            }

            return null;
        }
```

It's null if your Distributed Cache configuration has no Sliding Expiration nor Absolute Expiration, is that correct? It would mean items never expire?

**Comment by sudhinsr** [comment]
Yup exactly, But I'm not sure about the default value, I think for Redis implementation it's taking as infinite if the cache expiry is not set.
So maybe instead of throwing exception can we make it infinite expiry?

**Comment by ealsur** [comment]
For sure, I will fix it.

**Comment by ealsur** [comment]
@sudhinsr The fix is included in https://www.nuget.org/packages/Microsoft.Extensions.Caching.Cosmos/1.0.0-preview2

**Comment by sudhinsr** [comment]
Thank you @ealsur

**Comment by sudhinsr** [comment]
Thank you @ealsur 
Could please share the ETA for stable release ?

**Comment by ealsur** [comment]
No ETA yet, trying to gather feedback from usage to understand if we are missing any case before stable release. The more usage we get and feedback (like yours), the easier to determine if it's ready to release. We have test cases but it's hard to cover all scenarios (like your Redis replacement one).

**Comment by SirElTomato** [comment]
I'm having a similar issue, I've created a new issue [here](https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/issues/36). 

I'm using the latest preview version. 

Any thoughts? 

Thanks

**Comment by ealsur** [comment]
Issues are still addressed, we are planning to GA this semester.

**Comment by ealsur** [comment]
Just updating this issue, GA has already been done: https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos
