### ISSUE TITLE
Invalid TTL submitted in Request

### ISSUE THREAD

**Issue by paul-datatech911** [Azure/Microsoft.Extensions.Caching.Cosmos#79]
**Describe the bug**
Periodically checking for a value using the cache-aside pattern with both an absolute expiration and sliding expiration results in a unexpected exception.  Default TTL is also set to non-zero value.

**To Reproduce**  Repro uses absolute = 5s, sliding = 2s for brevity, but was happening in the wild for me with 60m & 30m respectively.
````csharp
[TestMethod]
public async Task TestActualCosmosCacheForTTLBug2()
{
	var cacheOptions = Options.Create<CosmosCacheOptions>(new CosmosCacheOptions()
	{
		ContainerName = Configuration["Cosmos:CacheContainer"],
		DatabaseName = Configuration["Cosmos:CacheDatabase"],
		ClientBuilder = new CosmosClientBuilder(Configuration["Cosmos:CacheConnectionString"]),
		CreateIfNotExists = true,
		DefaultTimeToLiveInMs = 60 * 1000
	});
	var cache = new CosmosCache(cacheOptions);

	string key = "abc";
	var cancelToken = CancellationToken.None;
	string? val1 = null;

	// Will generally throw an exception after a dozen or two attempts
	for (int i = 0; i < 100; i++)
	{
		// Cache-aside with both absolute & relative expiration
		if ((val1 = await cache.GetStringAsync(key, cancelToken)) == null)
		{
			val1 = await GetFromDataStore(key);
			await cache.SetStringAsync(key, val1, new DistributedCacheEntryOptions
			{
				AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(5),
				SlidingExpiration = TimeSpan.FromSeconds(2)
			},
			cancelToken);
		}	
		
		_log.Info($"Iter: {i}, Result: {val1}");
		Assert.IsNotNull(val1);
		await Task.Delay(TimeSpan.FromSeconds(Random.Shared.Next(10)));
	}

	Task<string> GetFromDataStore(string key)
	{
		return Task.FromResult("def");
	}
}
````

**Expected behavior**
Item should be retrieved from the cache if it is not expired, or set after datastore retrieval if it is not in the cache.  Expiration should be bumped via sliding expiration until absolute expiration is reached per docs - https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.distributed.distributedcacheentryoptions.slidingexpiration?view=dotnet-plat-ext-8.0.

**Additional context**
Request eventually fails with CosmosException indicating an invalid TTL=0 in request.
````
 Message: 

Test method FR911.Utils.Test.Core.TestDistributedCacheExtensions.TestActualCosmosCacheForTTLBug threw exception: 
Microsoft.Azure.Cosmos.CosmosException: Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: d2ac5161-144a-4f3d-b9b3-0c53cc87f4d9; Reason: (Message: {"Errors":["The input ttl '0' is invalid. Ensure to provide a nonzero positive integer less than or equal to '2147483647', or '-1' which means never expire."]}
ActivityId: d2ac5161-144a-4f3d-b9b3-0c53cc87f4d9, Request URI: /apps/56ada6bd-5a60-4436-9835-23212828207c/services/27cabfe7-e1a0-4bd4-8af9-5b3bb9434ca6/partitions/fe50de77-7880-4018-80af-91519337bdbc/replicas/133523528411934195p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Windows/10.0.22631 cosmos-netstandard-sdk/3.31.4);

  Stack Trace: 
StoreResult.ToResponse(RequestChargeTracker requestChargeTracker)
ConsistencyWriter.WritePrivateAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean forceRefresh)
BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
ConsistencyWriter.WriteAsync(DocumentServiceRequest entity, TimeoutHelper timeout, Boolean forceRefresh, CancellationToken cancellationToken)
<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy)
TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
````

**Comment by ealsur** [comment]
If both Absolute and Sliding expiration is configured:

https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/6fea577a6d8134d4429b5eea883ea6a5fd58f577/src/CosmosCache.cs#L343-L348

If the Absolute Expiration calculation is less than the Sliding Expiration, then the Absolute is used. The Min is basically doing what the documentation describes.

However, in this case, it is possible that the Absolute expiration calculation is reaching zero (or could be milliseconds but because TTL is seconds, it calculates as 0) and when attempted to be set, it obviously fails. 

Seems like the edge cause of "touching" the item when it's approaching absolute expiration. If this is during a Get - we could consider it an empty cache, if it's on a Set though, it would mean that the item cannot be updated (maybe a new item should be created?).

What's the full stack trace? Which of the 2 operations is throwing it?

**Comment by ealsur** [comment]
The stack trace might confirm but this might also be another scenario:

https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/6fea577a6d8134d4429b5eea883ea6a5fd58f577/src/CosmosCache.cs#L123-L126

In this case, this assignment is wrong. Instead of setting it to `0` (this is no the Get), it should just return `null`.

**Comment by paul-datatech911** [comment]
> If both Absolute and Sliding expiration is configured:
> 
> https://github.com/Azure/Microsoft.Extensions.Caching.Cosmos/blob/6fea577a6d8134d4429b5eea883ea6a5fd58f577/src/CosmosCache.cs#L343-L348
> 
> If the Absolute Expiration calculation is less than the Sliding Expiration, then the Absolute is used. The Min is basically doing what the documentation describes.
> 
> However, in this case, it is possible that the Absolute expiration calculation is reaching zero (or could be milliseconds but because TTL is seconds, it calculates as 0) and when attempted to be set, it obviously fails.
> 
> Seems like the edge cause of "touching" the item when it's approaching absolute expiration. If this is during a Get - we could consider it an empty cache, if it's on a Set though, it would mean that the item cannot be updated (maybe a new item should be created?).
> 
> What's the full stack trace? Which of the 2 operations is throwing it?

I believe it is the Set operation, but the stack doesn't make it clear.  Like I said before, I've gotten this exception in the wild when the Abs = 60mins and the Sliding = 30mins, so if the calculation is failing because it calculates and sends a 0s TTL and 0s TTL is illegal, I'd say that it's not the caller misbehaving, but the implementation.  I mean, you can use ANY expiration TimeSpan > 1s as an example, and if it calculates a 0TTL from that it shouldn't throw - at worst on a Get it should return null, and on a Set if the remaining TTL is too low it should re-set the data with the specified `DistributedCacheEntryOptions` params  Entire stack is below.

````
2024-03-24 06:21:16,589 Microsoft.Extensions.Hosting.Internal.Host fr911traumasoftworkers--i7f0sb0-7878f9bcff-7vgc4 ERROR BackgroundService failed
Microsoft.Azure.Cosmos.CosmosException : Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: ebc3ea30-af35-4019-af28-13fa268b06b6; Reason: (Message: {"Errors":["The input ttl '0' is invalid. Ensure to provide a nonzero positive integer less than or equal to '2147483647', or '-1' which means never expire."]}
ActivityId: ebc3ea30-af35-4019-af28-13fa268b06b6, Request URI: /apps/56ada6bd-5a60-4436-9835-23212828207c/services/27cabfe7-e1a0-4bd4-8af9-5b3bb9434ca6/partitions/fe50de77-7880-4018-80af-91519337bdbc/replicas/133523528411934195p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Linux/12 cosmos-netstandard-sdk/3.31.4);
   at Microsoft.Azure.Documents.StoreResult.ToResponse(RequestChargeTracker requestChargeTracker)
   at Microsoft.Azure.Documents.ConsistencyWriter.WritePrivateAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean forceRefresh)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)
   at Microsoft.Azure.Documents.ConsistencyWriter.WriteAsync(DocumentServiceRequest entity, TimeoutHelper timeout, Boolean forceRefresh, CancellationToken cancellationToken)
   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass31_0.<<InvokeAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)
   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)
   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)
--- Cosmos Diagnostics ---{"Summary":{"DirectCalls":{"(400, 0)":1}},"name":"ReplaceItemAsync","start datetime":"2024-03-24T06:21:16.493Z","duration in milliseconds":24.6043,"data":{"Client Configuration":{"Client Created Time Utc":"2024-03-24T03:21:06.3870002Z","MachineId":"hashedMachineName:38521cd9-f0e0-7930-5f1d-a83766084a08","NumberOfClientsCreated":1,"NumberOfActiveClients":1,"ConnectionMode":"Direct","User Agent":"cosmos-netstandard-sdk/3.35.4|1|X64|Debian GNU Linux 12 bookworm |.NET 8.0.3|N|Microsoft.Extensions.Caching.Cosmos","ConnectionConfig":{"gw":"(cps:50, urto:6, p:False, httpf: False)","rntbd":"(cto: 5, icto: -1, mrpc: 30, mcpe: 65535, erd: True, pr: ReuseUnicastPort)","other":"(ed:False, be:False)"},"ConsistencyConfig":"(consistency: NotSet, prgns:[], apprgn: )","ProcessorCount":1}},"children":[{"name":"ItemSerialize","duration in milliseconds":0.016},{"name":"Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler","duration in milliseconds":24.4708,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.DiagnosticsHandler","duration in milliseconds":24.4608,"data":{"System Info":{"systemHistory":[{"dateUtc":"2024-03-24T06:20:17.7604256Z","cpu":5.245,"memory":13297192.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0233,"availableThreads":32765,"minThreads":1,"maxThreads":32767},"numberOfOpenTcpConnection":6},{"dateUtc":"2024-03-24T06:20:27.7606388Z","cpu":4.421,"memory":13298940.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0489,"availableThreads":32765,"minThreads":1,"maxThreads":32767},"numberOfOpenTcpConnection":6},{"dateUtc":"2024-03-24T06:20:37.7608251Z","cpu":4.632,"memory":13302212.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0287,"availableThreads":32765,"minThreads":1,"maxThreads":32767},"numberOfOpenTcpConnection":6},{"dateUtc":"2024-03-24T06:20:47.7610055Z","cpu":6.657,"memory":13296276.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0245,"availableThreads":32765,"minThreads":1,"maxThreads":32767},"numberOfOpenTcpConnection":6},{"dateUtc":"2024-03-24T06:20:57.7612276Z","cpu":4.743,"memory":13300592.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0308,"availableThreads":32765,"minThreads":1,"maxThreads":32767},"numberOfOpenTcpConnection":6},{"dateUtc":"2024-03-24T06:21:07.7614123Z","cpu":3.957,"memory":13294648.000,"threadInfo":{"isThreadStarving":"False","threadWaitIntervalInMs":0.0353,"availableThreads":32765,"minThreads":1,"maxThreads":32767},"numberOfOpenTcpConnection":6}]}},"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RetryHandler","duration in milliseconds":24.4573,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.RouterHandler","duration in milliseconds":24.4456,"children":[{"name":"Microsoft.Azure.Cosmos.Handlers.TransportHandler","duration in milliseconds":24.4436,"children":[{"name":"Microsoft.Azure.Documents.ServerStoreModel Transport Request","duration in milliseconds":22.5248,"data":{"Client Side Request Stats":{"Id":"AggregatedClientSideRequestStatistics","ContactedReplicas":[{"Count":1,"Uri":"rntbd://cdb-ms-prod-westus3-be11.documents.azure.com:14316/apps/56ada6bd-5a60-4436-9835-23212828207c/services/27cabfe7-e1a0-4bd4-8af9-5b3bb9434ca6/partitions/fe50de77-7880-4018-80af-91519337bdbc/replicas/133523528411934195p/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-westus3-be11.documents.azure.com:14155/apps/56ada6bd-5a60-4436-9835-23212828207c/services/27cabfe7-e1a0-4bd4-8af9-5b3bb9434ca6/partitions/fe50de77-7880-4018-80af-91519337bdbc/replicas/133523528364434868s/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-westus3-be11.documents.azure.com:14178/apps/56ada6bd-5a60-4436-9835-23212828207c/services/27cabfe7-e1a0-4bd4-8af9-5b3bb9434ca6/partitions/fe50de77-7880-4018-80af-91519337bdbc/replicas/133523528411934194s/"},{"Count":1,"Uri":"rntbd://cdb-ms-prod-westus3-be11.documents.azure.com:14403/apps/56ada6bd-5a60-4436-9835-23212828207c/services/27cabfe7-e1a0-4bd4-8af9-5b3bb9434ca6/partitions/fe50de77-7880-4018-80af-91519337bdbc/replicas/133523528411934196s/"}],"RegionsContacted":[],"FailedReplicas":[],"AddressResolutionStatistics":[],"StoreResponseStatistics":[{"ResponseTimeUTC":"2024-03-24T06:21:16.5147629Z","ResourceType":"Document","OperationType":"Replace","LocationEndpoint":"https://fr911-westus3.documents.azure.com/","StoreResult":{"ActivityId":"ebc3ea30-af35-4019-af28-13fa268b06b6","StatusCode":"StartingErrorCode","SubStatusCode":"Unknown","LSN":42156,"PartitionKeyRangeId":"0","GlobalCommittedLSN":42156,"ItemLSN":-1,"UsingLocalLSN":false,"QuorumAckedLSN":42156,"SessionToken":"-1#42156","CurrentWriteQuorum":3,"CurrentReplicaSetSize":4,"NumberOfReadRegions":0,"IsValid":true,"StorePhysicalAddress":"rntbd://cdb-ms-prod-westus3-be11.documents.azure.com:14316/apps/56ada6bd-5a60-4436-9835-23212828207c/services/27cabfe7-e1a0-4bd4-8af9-5b3bb9434ca6/partitions/fe50de77-7880-4018-80af-91519337bdbc/replicas/133523528411934195p/","RequestCharge":1.67,"RetryAfterInMs":null,"BELatencyInMs":"0.517","ReplicaHealthStatuses":["(port: 14316 | status: Connected | lkt: 03/24/2024 03:21:15)"],"transportRequestTimeline":{"requestTimeline":[{"event": "Created", "startTimeUtc": "2024-03-24T06:21:16.4938234Z", "durationInMs": 0.0017},{"event": "ChannelAcquisitionStarted", "startTimeUtc": "2024-03-24T06:21:16.4938251Z", "durationInMs": 0.0042},{"event": "Pipelined", "startTimeUtc": "2024-03-24T06:21:16.4938293Z", "durationInMs": 0.0745},{"event": "Transit Time", "startTimeUtc": "2024-03-24T06:21:16.4939038Z", "durationInMs": 17.3435},{"event": "Received", "startTimeUtc": "2024-03-24T06:21:16.5112473Z", "durationInMs": 0.0208},{"event": "Completed", "startTimeUtc": "2024-03-24T06:21:16.5112681Z", "durationInMs": 0}],"serviceEndpointStats":{"inflightRequests":1,"openConnections":1},"connectionStats":{"waitforConnectionInit":"False","callsPendingReceive":0,"lastSendAttempt":"2024-03-24T06:21:11.4575885Z","lastSend":"2024-03-24T06:21:11.4576645Z","lastReceive":"2024-03-24T06:21:11.4787169Z"},"requestSizeInBytes":3735,"requestBodySizeInBytes":3228,"responseMetadataSizeInBytes":221,"responseBodySizeInBytes":159},"TransportException":null}}]},"Point Operation Statistics":{"Id":"PointOperationStatistics","ActivityId":"ebc3ea30-af35-4019-af28-13fa268b06b6","ResponseTimeUtc":"2024-03-24T06:21:16.5179630Z","StatusCode":400,"SubStatusCode":0,"RequestCharge":1.67,"RequestUri":"dbs/fr911cache/colls/cacheItems/docs/AgencySettings:dt911","ErrorMessage":"Microsoft.Azure.Documents.BadRequestException: Message: {\"Errors\":[\"The input ttl '0' is invalid. Ensure to provide a nonzero positive integer less than or equal to '2147483647', or '-1' which means never expire.\"]}\nActivityId: ebc3ea30-af35-4019-af28-13fa268b06b6, Request URI: /apps/56ada6bd-5a60-4436-9835-23212828207c/services/27cabfe7-e1a0-4bd4-8af9-5b3bb9434ca6/partitions/fe50de77-7880-4018-80af-91519337bdbc/replicas/133523528411934195p/, RequestStats: Microsoft.Azure.Cosmos.Tracing.TraceData.ClientSideRequestStatisticsTraceDatum, SDK: Linux/12 cosmos-netstandard-sdk/3.31.4\n   at Microsoft.Azure.Documents.StoreResult.ToResponse(RequestChargeTracker requestChargeTracker)\n   at Microsoft.Azure.Documents.ConsistencyWriter.WritePrivateAsync(DocumentServiceRequest request, TimeoutHelper timeout, Boolean forceRefresh)\n   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)\n   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)\n   at Microsoft.Azure.Documents.BackoffRetryUtility`1.ExecuteRetryAsync[TParam,TPolicy](Func`1 callbackMethod, Func`3 callbackMethodWithParam, Func`2 callbackMethodWithPolicy, TParam param, IRetryPolicy retryPolicy, IRetryPolicy`1 retryPolicyWithArg, Func`1 inBackoffAlternateCallbackMethod, Func`2 inBackoffAlternateCallbackMethodWithPolicy, TimeSpan minBackoffForInBackoffCallback, CancellationToken cancellationToken, Action`1 preRetryCallback)\n   at Microsoft.Azure.Documents.ConsistencyWriter.WriteAsync(DocumentServiceRequest entity, TimeoutHelper timeout, Boolean forceRefresh, CancellationToken cancellationToken)\n   at Microsoft.Azure.Documents.ReplicatedResourceClient.<>c__DisplayClass31_0.<<InvokeAsync>b__0>d.MoveNext()\n--- End of stack trace from previous location ---\n   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)\n   at Microsoft.Azure.Documents.ShouldRetryResult.ThrowIfDoneTrying(ExceptionDispatchInfo capturedException)\n   at Microsoft.Azure.Documents.RequestRetryUtility.ProcessRequestAsync[TRequest,IRetriableResponse](Func`1 executeAsync, Func`1 prepareRequest, IRequestRetryPolicy`2 policy, CancellationToken cancellationToken, Func`1 inBackoffAlternateCallbackMethod, Nullable`1 minBackoffForInBackoffCallback)\n   at Microsoft.Azure.Documents.StoreClient.ProcessMessageAsync(DocumentServiceRequest request, CancellationToken cancellationToken, IRetryPolicy retryPolicy)\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.ProcessMessageAsync(RequestMessage request, CancellationToken cancellationToken)\n   at Microsoft.Azure.Cosmos.Handlers.TransportHandler.SendAsync(RequestMessage request, CancellationToken cancellationToken)","RequestSessionToken":null,"ResponseSessionToken":"0:-1#42156","BELatencyInMs":"0.517"}}}]}]}]}]}]}]}

````

Also, in the `GetStringAsync(...)` call I often get the following Exception instead of just returning null as the source code suggests it should.  I do see where it says the GetStringASync(...) method can return stored exceptions the same as synchronous GetString(...), but neither the linked source or the [docs](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.caching.distributed.distributedcacheextensions.getstring?view=dotnet-plat-ext-8.0#microsoft-extensions-caching-distributed-distributedcacheextensions-getstring(microsoft-extensions-caching-distributed-idistributedcache-system-string)) mention any such exceptions:

````
  Message: 
Test method FR911.Utils.Test.Core.TestDistributedCacheExtensions.TestActualCosmosCacheForTTLBug2 threw exception: 
Microsoft.Azure.Cosmos.CosmosException: Response status code does not indicate success: NotFound (404); Substatus: 0; ActivityId: f06953f5-80fb-400a-bce1-a985019bba9e; Reason: (
Errors : [
  "Resource Not Found. Learn more: https://aka.ms/cosmosdb-tsg-not-found"
]
);

  Stack Trace: 
CosmosResponseFactoryCore.ProcessMessage[T](ResponseMessage responseMessage, Func`2 createResponse)
ContainerCore.ReplaceItemAsync[T](T item, String id, ITrace trace, Nullable`1 partitionKey, ItemRequestOptions requestOptions, CancellationToken cancellationToken)
ClientContextCore.RunWithDiagnosticsHelperAsync[TResult](String containerName, String databaseName, OperationType operationType, ITrace trace, Func`2 task, Func`2 openTelemetry, String operationName, RequestOptions requestOptions)
ClientContextCore.OperationHelperWithRootTraceAsync[TResult](String operationName, String containerName, String databaseName, OperationType operationType, RequestOptions requestOptions, Func`2 task, Func`2 openTelemetry, TraceComponent traceComponent, TraceLevel traceLevel)
CosmosCache.GetAsync(String key, CancellationToken token)
DistributedCacheExtensions.GetStringAsync(IDistributedCache cache, String key, CancellationToken token)
TestDistributedCacheExtensions.TestActualCosmosCacheForTTLBug2() line 287
````

**Comment by ealsur** [comment]
>  at worst on a Get it should return null, and on a Set if the remaining TTL is too low it should re-set the data with the specified DistributedCacheEntryOptions params Entire stack is below.

I think this is what should be the fix for the code linked in my above comments.

**Comment by ealsur** [comment]
I tested the repro with and without the linked PR and the exception goes away with the proposed fix.

**Comment by paul-datatech911** [comment]
> I tested the repro with and without the linked PR and the exception goes away with the proposed fix.

I'll add that if I only use AbsoluteExpiration on the DistributedCacheEntryOptions I don't see the TTL = 0 bug or the 404.  

I see the linked PR above and I think it looks good.  Thanks @ealsur
